blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/syxc/gh-repo-cli/discussions
    about: Use GitHub Discussions for questions about how to use gh-repo-cli
  - name: Feature Requests
    url: https://github.com/syxc/gh-repo-cli/issues/new?template=feature_request.md
    about: Use the feature request template to suggest new features
